name: bike_point_ingestion

on: 
  schedule:
  # every five minutes
    - cron: '*/5 * * * *'
  # allow the workflow to run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: .env
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
  
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
  
      - name: Install requirements
        run: pip install -r requirements.txt
  
      - name: Run python script
        env:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          bucket_name: ${{secrets.BUCKET_NAME}}
        run: python combined_bike_api.py
      
